class Lib::InputConstants

  DATES = [
    ['0000', '12:00 AM'],
    ['0030', '12:30 AM'],
    ['0100', '1:00 AM'],
    ['0130', '1:30 AM'],
    ['0200', '2:00 AM'],
    ['0230', '2:30 AM'],
    ['0300', '3:00 AM'],
    ['0330', '3:30 AM'],
    ['0400', '4:00 AM'],
    ['0430', '4:30 AM'],
    ['0500', '5:00 AM'],
    ['0530', '5:30 AM'],
    ['0600', '6:00 AM'],
    ['0630', '6:30 AM'],
    ['0700', '7:00 AM'],
    ['0730', '7:30 AM'],
    ['0800', '8:00 AM'],
    ['0830', '8:30 AM'],
    ['0800', '8:00 AM'],
    ['0830', '8:30 AM'],
    ['0900', '9:00 AM'],
    ['0930', '9:30 AM'],
    ['1000', '10:00 AM'],
    ['1030', '10:30 AM'],
    ['1100', '11:00 AM'],
    ['1130', '11:30 AM'],
    ['1200', '12:00 PM'],
    ['1230', '12:30 PM'],
    ['1300', '1:00 PM'],
    ['1330', '1:30 PM'],
    ['1400', '2:00 PM'],
    ['1430', '2:30 PM'],
    ['1500', '3:00 PM'],
    ['1530', '3:30 PM'],
    ['1600', '4:00 PM'],
    ['1630', '4:30 PM'],
    ['1700', '5:00 PM'],
    ['1730', '5:30 PM'],
    ['1800', '6:00 PM'],
    ['1830', '6:30 PM'],
    ['1900', '7:00 PM'],
    ['1930', '7:30 PM'],
    ['2000', '8:00 PM'],
    ['2030', '8:30 PM'],
    ['2100', '9:00 PM'],
    ['2130', '9:30 PM'],
    ['2200', '10:00 PM'],
    ['2230', '10:30 PM'],
    ['2300', '11:00 PM'],
    ['2330', '11:30 PM'],
  ]

  COUNTRIES = [
    "United States",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas, The",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burma",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cabo Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo, Democratic Republic of the",
    "Congo, Republic of the",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia, The",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territories",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ]
end
