# Restart webpack-watcher or webpack-dev-server if you make changes here
config: config/webpack
entry: packs
output: public
node_modules: node_modules
source: app/frontend
extensions:
  - .js
  - .jsx
  - .vue
  - .sass
  - .scss
  - .css
  - .png
  - .svg
  - .gif
  - .jpeg
